### ISSUE TITLE
Ability to process chunks or snippets in field options

### ISSUE THREAD

**Issue by hugopeek** [modmore/ClientConfig#104]
If you could use a chunk or snippet to generate the options, this would open up a whole array of possibilities. Related to #61 and #93.

**Comment by Mark-H** [comment]
Pull requests are welcome.

**Comment by Mark-H** [comment]
Added in 2.0, thanks :)

**Comment by Mark-H** [comment]
To give an example of how this works before I update the docs. Add a snippet or chunk tag to the options field, for example:

````
[[getResources? &parents=`0` &tpl=`@INLINE [[+pagetitle]]==[[+id]]` &outputSeparator=`||` &limit=`0` ]]
````
and enable the "Process tags in options" checkbox. 

![schermafbeelding 2017-10-04 om 00 15 21](https://user-images.githubusercontent.com/312944/31151723-12ca2622-a899-11e7-8ad9-c83f5ce1752d.jpg)
