### ISSUE TITLE
Not using full Media Source Path on Image Field

### ISSUE THREAD

**Issue by cottoncreative** [modmore/ClientConfig#124]
### Summary
When using the Image field with a Media Source the img src path doesn't include the media source base_url so the image can't be found.

### Step to reproduce
Create Media Source and add it to the Image Field. 
Choose Image from selected source and save.
Preview site.

### Observed behavior
Image source only shows path displayed in the image field box.
```<img src="img.jpg">```

### Expected behavior
Should pull in the Media Source base path/url
```<img src="/path/to/media/source/img.jpg">```

### Environment
ClientConfig v1.4.1, MODX 2.5.4

**Comment by Mark-H** [comment]
Fixed in 2.0
