### ISSUE TITLE
Fix namespace assets path

### ISSUE THREAD

**Issue by labr1005** [modmore/ClientConfig#126]
### Summary
Just take a look at the namespace assets path after install.

### Environment
ClientConfig 1.4.1, MODX 2.5.5

**Comment by Mark-H** [comment]
Is this causing any issues for you? AFAIK, that path is not used anywhere.

**Comment by labr1005** [comment]
No issues.

**Comment by Mark-H** [comment]
Should be fixed in 1.4.2, but only on new installs probably.
