### ISSUE TITLE
Minor Layout Quirk

### ISSUE THREAD

**Issue by EkoOne** [modmore/ClientConfig#128]
In all of the CC-related pages the heading is positioned too far to the left compared to the rest of the Manager page headings.

![client-config-1](https://cloud.githubusercontent.com/assets/1754223/23819605/f35596aa-05cd-11e7-9584-b818afb97b52.png)

![client-config](https://cloud.githubusercontent.com/assets/1754223/23819606/f36c31ee-05cd-11e7-9453-73aa845b6a12.png)

**Comment by Mark-H** [comment]
Thanks @EkoOne!
