### ISSUE TITLE
Error when saving

### ISSUE THREAD

**Issue by mishantrop** [modmore/ClientConfig#129]
### Summary
	[2017-04-22 04:27:02] (ERROR @ /.../core/xpdo/om/xpdoobject.class.php : 1452) Error HY000 executing statement:
	INSERT INTO `modx_clientconfig_setting` (`key`, `label`, `xtype`, `description`, `is_required`, `sortorder`, `value`, `default`, `group`, `options`, `source`) VALUES ('phone', 'Phone', 'textfield', '', 0, 0, '123-456', '', 1, '', 0)
	Array
	(
		[0] => HY000
		[1] => 1366
		[2] => Incorrect integer value: '' for column 'source' at row 1
	)
![1](https://cloud.githubusercontent.com/assets/5341208/25300430/d642c93c-2717-11e7-88db-6b4e11abf00e.jpg)
![2](https://cloud.githubusercontent.com/assets/5341208/25300432/d8267e7e-2717-11e7-8bda-f2ef67841f48.jpg)
![3](https://cloud.githubusercontent.com/assets/5341208/25300433/d96aff3a-2717-11e7-96b7-68316c9e5d93.jpg)

### Step to reproduce
1. Create new setting.
2. Get error.

### Environment
ClientConfig 1.4.1-pl, MODX 2.5.7, Windows 7, MySQL 5.7, PHP 7.0.

**Comment by Mark-H** [comment]
Fixed in 1.4.2
