### ISSUE TITLE
Latest version not in Modx Extras Repository

### ISSUE THREAD

**Issue by getandyjones** [modmore/ClientConfig#131]
### Summary
I have an issue with php V 5.3.3 - when scouring the forums, it seems that the latest commit isn't available on the Modx Extras. I understand from Bob Ray it was a recent upload to be compatible with 5.3.3

**Comment by Mark-H** [comment]
Correct, I've been meaning to review the open pull requests before releasing 1.4.2. You can apply [the fix](https://github.com/modmore/ClientConfig/commit/3f1a716c13f0c4d28e7430f70752e22c616eb780) manually for now.

**Comment by Mark-H** [comment]
For future reference in case someone stumbles across this, I tend to release updates on modmore.com faster. That's like 3 clicks of work for me, while to update modx.com I need to update the version info, build a package, go to the modx site, find clientconfig, find the right button, fill in all the version info that's also in the package, and finally upload the transport zip.

**Comment by Mark-H** [comment]
1.4.2 is now available from both modmore.com and modx.com. Do note that PHP 5.3 compatibility is going away in the next release.
