### ISSUE TITLE
Language specific characters error

### ISSUE THREAD

**Issue by pawelmil** [modmore/ClientConfig#132]
Polish language characters in eg. text or textarea box change to "?" signs after saving and refreshing manager page. There is no problem with encoding in normal Modx template variables.

### Environment
ClientConfig 1.4.1, MODX 2.5.7, SQL character encoding utf8

**Comment by Mark-H** [comment]
Sounds like the tables in your database don't have the right charset. The charset can differ per server, database, table and even column, so it happens pretty often that some of those are not created with the right charset if the server default is different from the chosen one for the database.

**Comment by pawelmil** [comment]
You're right. After changing clientconfig tables charset it works fine. Thank you.
