### ISSUE TITLE
Client config to play nice with Context Router

### ISSUE THREAD

**Issue by gleighfield** [modmore/ClientConfig#136]
### Summary
Tried the new client config v2 with a multi context setup, and I'd like to put key field in client config, as the UI is much nicer than the standard MODX context one.

### Steps to reproduce
Add in site_url, http_host, base_url and site_start into client config from a current working multi context setup.

### Observed behavior
Nothing works :( 

### Expected behavior
Everything should work!

### Environment
ClientConfig V2 pre-release, MODX 2.5.7

**Comment by Mark-H** [comment]
Ah, that's what you're trying to do! 

There's one rather tricky problem with putting the actual context configuration into ClientConfig, which is that CC needs to _know what context is loaded_ for it to apply its settings. While they're called context settings, they aren't _really_ context settings, it just fetches the right values when MODX is being initiated.

Or put another way. ContextRouter needs to run before ClientConfig can apply its settings. 

Might need some out-of-the-box thinking to address this one...

**Comment by gleighfield** [comment]
Ah, I did wonder about that, I tried changing the plugin firing order for the event between the two, and it didnt' work either :(

**Comment by jonleverrier** [comment]
Would this be the same for XRouting? I can't get the multi context settings to work!

**Comment by Mark-H** [comment]
Yes, the same problem would apply to XRouting. 

It's a chicken and egg problem. ClientConfig bases its context-specific "settings" on the _current context_. Those "settings" are then dynamically loaded in a way that it overrides what's configured elsewhere.

XRouting, ContextRouter etc, look at actual context settings (note: ClientConfig does not store its values as actual context settings, it uses its own tables) to determine _what context to set_. So context routing plugins need to run before ClientConfig for ClientConfig to set the right values, thus ClientConfig values can't be used for context routing.

**Comment by Mark-H** [comment]
Short of rewriting ClientConfig to update actual context and system settings, instead of its own tables and dynamically overriding the MODX stuff, I'm not sure how this would be solvable.

**Comment by jonleverrier** [comment]
No problems @Mark-H.

Perhaps a snippet might work to retrieve CB settings in environments that use XRouting/ContentRouter ?

**Comment by Mark-H** [comment]
xRouting/ContextRouter/whatever router just need to be updated to run sooner. #140

**Comment by Mark-H** [comment]
Related to the opening request (adding site_url and such into ClientConfig) - that's going to be near impossible to solve. Also I don't think such settings should be editable by clients - but that's a different discussion.

For any other custom (non-routing related) context settings, it's easy to fix. Depending on the router, either adjust their plugin to use OnMODXInit, or adjust the ClientConfig plugin to use OnHandleRequest. https://github.com/modmore/ClientConfig/issues/140#issuecomment-367294057

**Comment by Mark-H** [comment]
Closing as CC will now run on both OnHandleRequest and OnMODXInit events, which should resolve any issues with a router running after CC.

**Comment by brockmarek** [comment]
This fixed it for me as far as any other settings. But I keep the xrouting settings in context settings.
https://docs.modx.com/current/en/building-sites/contexts/gateway-plugin
