### ISSUE TITLE
Dublicate text

### ISSUE THREAD

**Issue by Pfeifakopf** [modmore/ClientConfig#142]
Please add a configuration for "_duplicate" to change the text or let it empty. To delete it mulitple times is really annoying.

**Comment by Mark-H** [comment]
I'm assuming you mean for duplicating settings or groups? Please be a bit more detailed when opening issues so we don't have to guess what you're talking about. 

PR for this is welcome.

**Comment by Pfeifakopf** [comment]
Sorry, i've forgotten this ticket. I meant, when you duplicate an element like a snippet or a chunk. By default there is always at the end of the duplicated item name the text "_duplicate"  added.

**Comment by Mark-H** [comment]
Sounds like you may have meant to create an issue in the Revolution repository instead - this tracker is for the ClientConfig extra ;)

**Comment by Mark-H** [comment]
Fixed in 2.0.0-pl.
