### ISSUE TITLE
Image selected from media source does not render the media source path on the image

### ISSUE THREAD

**Issue by intersel** [modmore/ClientConfig#146]
### Summary
A setting with a field type "image" and with a media source set, when used, the path of the media source is not rendered

### Step to reproduce
- create a setting with field type "image" and a media source
- choose an image for the setting
- use it in a resource 

### Observed behavior
the setting is rendered only with the image name without any path

### Expected behavior
the setting should be rendered with the path of the media source then the image name

### Environment
ClientConfig 1.4.2, Modx 2.6.3, Debian, mysql server 5.5.53, php 7.0

**Comment by Mark-H** [comment]
This is fixed in clientconfig 2. https://www.modmore.com/blog/2017/clientconfig-2-context-settings/

I wont be fixing this in 1.4.x as it would be breaking behaviour that's been like that for a while now.

**Comment by intersel** [comment]
OK! I was not aware of V2...
I'll migrate to it asap... 
Thanks...
