### ISSUE TITLE
Multi-context not loading/refreshing image or file fields

### ISSUE THREAD

**Issue by jcdm** [modmore/ClientConfig#147]
### Summary
When a file or image field type is saved in multi-context it is correctly written for retrieval, but on the next load those fields show the default value instead of the saved one, saving over the top of the existing value on save. This seems to occur whether the types are using a custom media source or using the basic 'Filesystem'

### Step to reproduce
Create a file or image type setting on a multi-context site, select a file/image, save. Then load the context again by visiting the page and selecting the context from the menu.

### Observed behavior
The field contains whatever the default is.

### Expected behavior
It should be showing the previously save file reference

### Environment
CC 2.0.0-rc1 & -pl
MODX 2.6.3-pl
PHP 7.1.1
OS MODX Cloud

**Comment by jcdm** [comment]
I'm so sorry to be having this issue 10 hours after you went to pl 😣

**Comment by jcdm** [comment]
I can confirm that the connector.php response on context change is providing the correct value in the returned object, so it just appears that it's not being updated in the input box itself.

**Comment by sebastian-marinescu** [comment]
Just ran into this, cause I'm having a multi-context multi-language site coming up with 4 different logos, which I wanted to conveniently manage through ClientConfig ;)
Changing it to text-type, retrieves the correctly set value. I'll stick with text until it's fixed, but officially: +1
And great work on the fix @jcdm :+1:

**Comment by Mark-H** [comment]
Fixed in 2.1
