### ISSUE TITLE
Event priority clobbered on update

### ISSUE THREAD

**Issue by jcdm** [modmore/ClientConfig#148]
### Summary
I set ClientConfig's priority to something above 0 to ensure it executes after XRouting so a route is successfully set. On update, the priority setting I had in place was removed, breaking ClientConfig settings until it was reset.

### Step to reproduce
Have ClientConfig installed, set the plugin to a priority other than one and then perform an upgrade.

### Observed behavior
The priority against the OnMODXInit event is set to 0.

### Expected behavior
Ideally it should remain to whatever it was set to before.

### Environment
CC 2.0.0-pl, MODX 2.6.3, MacOS, MariaDB 5.0.11 and PHP 5.6.25 (running on Mac localhost)
Also has happened on CC 2.0.0-pl, MODX 2.6.3, MODX Cloud w/ PHP 7.1

**Comment by Mark-H** [comment]
As of 2.1, the events won't be overwritten anymore.
