### ISSUE TITLE
[€50] Feature Request: Divider for categories / tab content

### ISSUE THREAD

**Issue by pepebe** [modmore/ClientConfig#149]
### Summary
Structuring a group of config settings by group is a nice feature. 

As there are not subcategories at the moment, it would be nice to have a "fake" input type which displays a header instead of an actual input field.

![bildschirmfoto 2018-07-06 um 12 30 56](https://user-images.githubusercontent.com/667315/42374461-7c38adf6-8118-11e8-9ebe-6a8631e1cc69.png)

### Pros
A fake input type can be positioned within a category. 
We don't need to build a subcategory logic

### Expected behavior
Cons its fake.
There might be issues on save

**Comment by Mark-H** [comment]
Good idea (similar to #84, this one being easier to implement), but let's not call it a "fake" input. Call it a divider, or something. It wouldn't have issues on save if it's implemented as a panel that doesn't have a name field.

Happy to provide a €50 bounty or €75 modmore credit to whoever sends a pull request with this.

**Comment by pepebe** [comment]
A simple divider instead of a tab would be much easier to implement. I'll have a look at the source and think about how to do that. 

BTW: Is there any chance that CB elements might be available inside CC?

**Comment by Mark-H** [comment]
CB elements in CC? How do you imagine that working?

**Comment by Mark-H** [comment]
Added a simple line field in 2.3.
