### ISSUE TITLE
Image xtype gets extra slash prefixed

### ISSUE THREAD

**Issue by muzzwood** [modmore/ClientConfig#150]
### Summary
Extra slash prefixed on url

### Step to reproduce
Output an image from Clientconfig. 

### Observed behavior
An extra slash will be at the beginning even though your media source doesn't have one.
With the old version the media source wasn't being added to the URL at all so it's great that it now is. It just needs to output the media source url correctly now.

### Expected behavior
It should be the same as the media source

### Environment
ClientConfig 2.0, MODX 2.6.5

**Comment by Mark-H** [comment]
This may need some more information. It's handing over prefixing of the url to the media source, so that should be the same, but you've not provided the details for the media source configuration/expected/observed for me to try to reproduce this.

**Comment by digitalpenguin** [comment]
Apologies. I have some work coming up for the specific site I noticed it on so I'll re-test it and try to come up with a PR for it if still an issue.

**Comment by muzzwood** [comment]
Closing as it was too long ago to remember the specifics, and I haven't noticed a problem since. Most likely just a change in behaviour from v1 to v2.
