### ISSUE TITLE
Takes settings from the wrong context

### ISSUE THREAD

**Issue by faradaytrs** [modmore/ClientConfig#151]
### Summary
After update i chose multilingual option. But when i change settings in the second context, website still takes settings from the default one.
### Step to reproduce
i don't know what is it related to
### Observed behavior
ru context version takes configuration from the "web" one

### Expected behavior
ru context should take configuration from "ru"
### Environment
ClientConfig 2.0.0, MODX version 2.6.5, Operating System ubuntu 18.04, MySQL version 5.7.22, PHP version 7.2.7

**Comment by kwazaro** [comment]
My context switching takes place OnHandleRequest (custom plugin for context switching based on request cultureKey GET property), and CC runs OnMODXInit by default. So what is the right way to go in this case?
