### ISSUE TITLE
Media Source path shown on front end when Image field is left blank

### ISSUE THREAD

**Issue by cottoncreative** [modmore/ClientConfig#152]
### Summary
Media Source path being included in front end even when no content is included in the config and shows a blank image.

### Step to reproduce
– Create a image config with a media source
– Leave config blank
– add config to template with notempty/not modifier
– View site

### Observed behavior
Path to media source folder is still show so Config is seen as populated and shows blank image on front end. `<img src="path/to/media/source/" />`

### Expected behavior
Nothing should be shown on the front end if Config is left blank

### Environment
ClientConfig v2.0.0-pl, MODX 2.6.5

**Comment by Mark-H** [comment]
Also reported by Sander via support.

**Comment by massimiliano-bizen** [comment]
HI @Mark-H - we encountered the same issues, could you update us on this PR?

Maybe we could copy the Magento 2 solutions for the same "problem"? 
![image](https://user-images.githubusercontent.com/43063192/62132712-db672f80-b2dd-11e9-9518-0ec297186bda.png)

**Comment by Mark-H** [comment]
@massimiliano-bizen I believe the PR in #167 should fix this, but haven't had the time to test it yet. If you can try that and report back on the PR if it resolves the problem for you, then that would be very useful.

**Comment by Mark-H** [comment]
Fixed in the next release.
