### ISSUE TITLE
ClinetConfig and XRouting

### ISSUE THREAD

**Issue by jdaehne** [modmore/ClientConfig#154]
### Summary
Client Config is not working correct with the Plugin XRouting in the context-aware mode.

### Step to reproduce
install xRouting and ClinetConfig an try to show the different settings.

### Observed behavior
I could fix this issue by replacing line 36 in the ClientConfig Snippet from
`OnMODXInit` to `OnHandleRequest`.
Maybe it is possible to add this event to the snippet and set its priority to 10 or something higher than 0. Like:
```
case 'OnMODXInit':
case 'OnHandleRequest':
```

### Expected behavior
It should show the system settings.

### Environment
ClientConfig 2.0, MODX 2.65

**Comment by Mark-H** [comment]
Related to #140 and #136 

Introduced per #109

**Comment by sebastian-marinescu** [comment]
I had the same issue, and added 'OnHandleRequest' as suggested - now it works :+1:

**Comment by Mark-H** [comment]
I've added the suggested code from @jdaehne to the plugin in 2.1 so you can easily tick the OnHandleRequest event and have it run on the same event.
