### ISSUE TITLE
Incorrect value of the icon in the top menu

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modmore/ClientConfig#157]
If move the menu item "Configuration" from the "Extras" section in top menu MODX, the wrong icon path appears instead of the icon.

![top_menu_error](https://user-images.githubusercontent.com/12523676/48564999-effec580-e910-11e8-98a2-0c5b868dc446.png)

It is better to change, for example, to: `<i class="icon icon-wrench"></i>`

**Comment by Mark-H** [comment]
I've removed the icon in 2.1, didn't even realise that was being added ;)

**Comment by Ruslan-Aleev** [comment]
:) It is not necessary to completely delete the icon, should replace with FontAwesome icon, to mark the menu item
