### ISSUE TITLE
Context issue with getOption

### ISSUE THREAD

**Issue by studiorobl** [modmore/ClientConfig#164]
When using $modx->getOption('key') the setting is not available in one of my contexts, but is in the other context.

When I place it as a placeholder (i.e. [[++key]]) it works in either context.

I have updated to 2.1.0

**Comment by Mark-H** [comment]
This is most likely a result of what context routing solution you use, and where you're calling `$modx->getOption` exactly. 

See #136 (ContextRouter), #154 (XRouting) and #140 (Babel) for similar issues and discussions.
