### ISSUE TITLE
Get direct link to a category

### ISSUE THREAD

**Issue by Spheerys** [modmore/ClientConfig#169]
I'm using QuickButton and I would be hable to make a link to a direct ClientConfig's category/tab

Is it possible to get the wanted tab with a parameter on the URL ?

**Comment by Mark-H** [comment]
Added to 2.3.

Works by providing a URL hash with the **ID** of a group. So if the ID of the group (shown in the admin panel) is 2, the URL to use would be `/manager/?a=home&namespace=clientconfig#2`

**Comment by Spheerys** [comment]
I have updated ClientConfig to 2.3.0, delete the cache, but even with the #id after the url, it is the latest opened tab which is active after clicking on the button...

**Comment by Mark-H** [comment]
Tried in incognito mode or a different browser to ensure that's not because of browser caches?

**Comment by Spheerys** [comment]
Oh sorry, it was this ! It's working well, thanks ;)
