### ISSUE TITLE
Make it possible to set height for the text area field

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modmore/ClientConfig#172]
### Summary
It would be useful if the height of the field could be set for the text area field.

Now the height is very small, see the picture below:

![textarea](https://user-images.githubusercontent.com/12523676/64115359-74d3a680-cda0-11e9-800f-49d4ab1324ba.png)

Of course, you can use the "editor" field type, but they do not always work correctly - https://github.com/modmore/ClientConfig/issues/102

**Comment by Mark-H** [comment]
Would it be acceptable if it were just always bigger?

Or perhaps grows with the content?

**Comment by Ruslan-Aleev** [comment]
It’s better to initially make the field a larger in height (2,5x times, for example) + grows with the content :)

**Comment by Ruslan-Aleev** [comment]
@Mark-H why did you close this issue? Will there be a solution in the future?

**Comment by Mark-H** [comment]
Yeah, made it larger and autogrowing in upcoming 2.3. Just haven't pushed the code yet. :)

**Comment by Ruslan-Aleev** [comment]
Nice, thanks a lot!
