### ISSUE TITLE
Seems to block context clues

### ISSUE THREAD

**Issue by excelerondesign** [modmore/ClientConfig#179]
I have a site where i have a sub domain based off of a second context, the problem that i was having was that i was trying to use some content based off of the context settings but the placeholders kept pulling from the system setting instead of the setting from the individual context.
I uninstalled ClientConfig and this all corrected itself.
MODx version 2.7.2
ClientConfig version 2.3.0

**Comment by Mark-H** [comment]
Sorry @excelerondesign but this report is way too light on details for me to do anything with. 

What type of content? Where is that content stored? How are you handling context routing? Multi context mode enabled in ClientConfig?

**Comment by excelerondesign** [comment]
as per your question about routing i installed gateway manager and now it working fine.
