### ISSUE TITLE
Fieldtype Code (ACE) - Fullscreen function covers first Lines

### ISSUE THREAD

**Issue by domindian** [modmore/ClientConfig#184]
When you use the fieldtype Code and click into the symbol in the top right corner to toggle fullscreen view the field is covered by the modx main menu. The first lines and the toggle-icon itself are inaccessible

ClientConfig version 2.3.0-pl, MODX version 2.7.3-pl, Operating System Windows, PHP version 7.x,

**Comment by Mark-H** [comment]
Screenshot could be useful.

Does this site also use redactor 3 by chance?

**Comment by domindian** [comment]
have no screenshot at the moment. Yes it uses redactor3

**Comment by Mark-H** [comment]
I'm pretty sure it's Redactor 3 causing it then - there's a known issue with that, which I expect to fix in the next week or two. Closing this in the meantime as it's in my Redactor tracker already.
