### ISSUE TITLE
Context-Aware Dropdown Sort-Order

### ISSUE THREAD

**Issue by sebastian-marinescu** [modmore/ClientConfig#188]
### Summary
Currently the context-dropdown doesn't acknowledge the sort-order (rank) of contexts. 

### Expected behavior
Display the contexts in the context-dropdown in their configured order/rank. 

I'm going to take a look at it myself.

**Comment by muzzwood** [comment]
Yeah it looks like the core processor sets the default sort field as `key` rather than `rank`. So that would need to be overridden, or a sort param passed (there currently isn't one). I'll get this sorted (sorry! 😛 ) now.

**Comment by muzzwood** [comment]
Fixed in https://github.com/modmore/ClientConfig/commit/1eceff92a52f91bcabb791d76000d90670c90781
