### ISSUE TITLE
Extra asterisks required field in MODX 3

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modmore/ClientConfig#189]
### Summary
Extra asterisks required field in MODX 3:

![cc](https://user-images.githubusercontent.com/12523676/161401221-01246bbd-9552-40da-b62f-990a7ac41e2c.png)

### Environment
clientconfig-2.3.0-pl, MODX 3

**Comment by muzzwood** [comment]
Fixed in https://github.com/modmore/ClientConfig/commit/ecaaa7b1a43385a884736b3f72066f6a51521d3b

Thanks for reporting it @Ruslan-Aleev !
