### ISSUE TITLE
3.0 context dropdown doesn't work

### ISSUE THREAD

**Issue by Mark-H** [modmore/ClientConfig#193]
### Summary
Dropdown throws a fatal error due in 3.0 due to the inclusion of the old processor. 

( ! ) Fatal error: require_once(): Failed opening required '/Users/mhamstra/Sites/development.local/3.x/core/model/modx/processors/context/getlist.class.php' (include_path='.:/Applications/MAMP/bin/php/php7.4.21/lib/php') in /Users/mhamstra/Sites/development.local/ClientConfig/core/components/clientconfig/processors/mgr/contexts/getlist.class.php on line 2

### Step to reproduce
Enable context aware mode, try to switch contexts.

### Observed behavior
Should show contexts.

### Expected behavior
Throws error. Depending on server config, can also be a "200 OK" MODX popup. 

### Environment
Any.

**Comment by muzzwood** [comment]
Fixed in commit https://github.com/modmore/ClientConfig/commit/abe1c457d16d4e0ad89b3e11fd79fcf788f8a8be
