### ISSUE TITLE
Redactor in context mode

### ISSUE THREAD

**Issue by Jako** [modmore/ClientConfig#199]
### Summary
A redactor field shows/saves the same value in all contexts in context mode. A Textfield switches the value, when the context is switched.

### Step to reproduce
Add a redactor field in context mode.

### Environment
ClientConfig 2.3.3 
MODX 3.0.1

**Comment by Mark-H** [comment]
Additional info from S38178 suggests toggling view source in redactor makes it switch the values. We're also tracking this from Redactor in the internal tracker modmore/Redactor#510

**Comment by muzzwood** [comment]
This fixes the issue: https://github.com/modmore/ClientConfig/pull/208/files
