### ISSUE TITLE
Per-context settings? [$250]

### ISSUE THREAD

**Issue by Mark-H** [modmore/ClientConfig#4]
Possibly by assigning groups to one or more contexts.

**Comment by jpdevries** [comment]
+1

**Comment by matdave** [comment]
+1

**Comment by degoya** [comment]
+1

**Comment by Mark-H** [comment]
I started working on this in #123, a lot more detail is in that pull request.

**Comment by sebastian-marinescu** [comment]
I'd also love to see a solution to this. Just stumbled upon this while planning a multi-domain-setup. 

Right now, if I see correctly, I cannot even use context-specific settings to differ between contexts, because CC will override everything – am I seeing this correctly?

**Comment by Mark-H** [comment]
Correct.

**Comment by Mark-H** [comment]
This has been implemented, clientconfig 2.0-rc1 will be available from the modmore provider shortly in the pre-releases channel. 

I added #134 to discuss the need for more explicit access to permissions.

**Comment by Mark-H** [comment]
2.0.0-rc1 is now available from the Pre-releases channel on modmore. Will publish an announcement and update the docs later this week.
