### ISSUE TITLE
Category header, settings and lexicon

### ISSUE THREAD

**Issue by pepebe** [modmore/ClientConfig#91]
MODx settings for 'show_tv_categories_header' and the modx lexicon string for 'categories'  are used for clientconfig.

I don't think that TVs and ClientConfig should share the same settings.

Please consider a dedicated header setting (clientconfig.show_tv_categories_header ) and a separate lexicon entry (in core/components/clientconfig/lexicon/XX/default.inc.php).

Cheers,

pepebe

**Comment by Mark-H** [comment]
As of 2.0 this is using the `clientconfig.categories` lexicon instead.
